export_json.data:
  path: '/get_json/{node}'
  defaults:
    _controller: '\Drupal\site_config\Controller\SiteConfigController::content'
    _title: 'Retrieve Node'
  requirements:
    _permission: 'access content'