<?php


function site_config_form_system_site_information_settings_alter(&$form, $form_state, $form_id) {
  $form['site_information']['siteapikey'] = array(
    '#type' => 'textfield',
    '#title' => t('Site API Key'),
    '#default_value' =>  \Drupal::config('system.site')->get('siteapikey') ?: 'No API Key yet'
  );
  $form['actions']['submit']['#value'] = t('Update configuration');
  $form['#submit'][] = 'site_config_handler';
}

function site_config_handler($form, &$form_state) {
  \Drupal::configFactory()->getEditable('system.site')->set('siteapikey',  $form_state->getValue('siteapikey'))->save();
   drupal_set_message("Successfully set Site API Key to " . $form_state->getValue('siteapikey'));
}
